export const python = [
  {
    label: "print",
    detail: "打印输出",
    type: "function",
    info: "最常用的输出函数，把内容打印到屏幕；sep 控制分隔符，end 控制行尾。",
    boost: 100,
    apply: "print()",
  },
  {
    label: "input",
    detail: "读取输入",
    type: "function",
    info: "读取一行输入并返回字符串，可以传入提示文字。",
    boost: 99,
    apply: "input()",
  },
  {
    label: "len",
    detail: "获取长度",
    type: "function",
    info: "返回序列或集合的长度，常用来统计列表、字符串中有多少个元素。",
    boost: 90,
    apply: "len()",
  },
  {
    label: "range",
    detail: "生成整数序列",
    type: "function",
    info: "生成整数序列，支持起点、终点和步长，常配合 for 循环遍历次数。",
    boost: 85,
    apply: "range()",
  },
  {
    label: "enumerate",
    detail: "枚举索引与值",
    type: "function",
    info: "遍历时同时得到索引和值，可用 start 指定起始编号，适合需要编号输出的场景。",
    boost: 82,
    apply: "enumerate()",
  },
  {
    label: "zip",
    detail: "并行遍历",
    type: "function",
    info: "把多个可迭代对象按位置打包成元组并行遍历，长度取最短的序列。",
    boost: 80,
    apply: "zip()",
  },
  {
    label: "map",
    detail: "映射函数",
    type: "function",
    info: "把函数作用到序列每个元素，返回惰性迭代器，需要 list() 展开后才能看到结果。",
    boost: 78,
    apply: "map()",
  },
  {
    label: "filter",
    detail: "过滤元素",
    type: "function",
    info: "保留函数返回真值的元素，返回惰性迭代器，常用于筛选出符合条件的数据。",
    boost: 76,
    apply: "filter()",
  },
  {
    label: "sorted",
    detail: "排序",
    type: "function",
    info: "返回排好序的新列表，支持 key 排序函数和 reverse 逆序，不会修改原序列。",
    boost: 74,
    apply: "sorted()",
  },
  {
    label: "sum",
    detail: "求和",
    type: "function",
    info: "对可迭代对象求和，可设置初始值，常用于数字累计与前缀和。",
    boost: 72,
    apply: "sum()",
  },
  {
    label: "open",
    detail: "文件读写",
    type: "function",
    info: "打开文件获得文件对象，常配合 with 自动关闭，支持读写追加等多种模式。",
    boost: 70,
    apply: "open()",
  },
  {
    label: "abs",
    detail: "绝对值",
    type: "function",
    info: "返回数字的绝对值，把负数变成正数，常用于距离或差值计算。",
    boost: 68,
    apply: "abs()",
  },
  {
    label: "round",
    detail: "四舍五入",
    type: "function",
    info: "按指定小数位四舍五入，默认保留到整数，适合处理成绩或金额保留位数。",
    boost: 66,
    apply: "round()",
  },
  {
    label: "isinstance",
    detail: "类型检查",
    type: "function",
    info: "判断对象是否属于某个类型或类型元组，常用于分支处理不同数据。",
    boost: 64,
    apply: "isinstance()",
  },
  {
    label: "type",
    detail: "获取类型",
    type: "function",
    info: "返回对象的类型，或用三个参数动态创建类型，用来了解变量真实类型。",
    boost: 62,
    apply: "type()",
  },
  {
    label: "list",
    detail: "列表构造",
    type: "function",
    info: "把可迭代对象转换为列表，或创建空列表存放数据，支持列表推导式。",
    boost: 60,
    apply: "list()",
  },
  {
    label: "dict",
    detail: "字典构造",
    type: "function",
    info: "根据映射或键值对序列创建字典，用来存储键值对信息。",
    boost: 58,
    apply: "dict()",
  },
  {
    label: "set",
    detail: "集合构造",
    type: "function",
    info: "把可迭代对象转换为集合，自动去重，适合判重和集合运算。",
    boost: 56,
    apply: "set()",
  },
  {
    label: "tuple",
    detail: "元组构造",
    type: "function",
    info: "把可迭代对象转换为元组，或创建不可变的序列，用作安全的组合数据。",
    boost: 54,
    apply: "tuple()",
  },
  {
    label: "int",
    detail: "转整数",
    type: "function",
    info: "把参数转为整数，支持进制转换，如 int('101', 2) 表示二进制转十进制。",
    boost: 74,
    apply: "int()",
  },
  {
    label: "float",
    detail: "转浮点数",
    type: "function",
    info: "把参数转为浮点数，接受字符串或数字，常用于保留小数的计算。",
    boost: 72,
    apply: "float()",
  },
  {
    label: "str",
    detail: "转字符串",
    type: "function",
    info: "把对象转为字符串，常用于输出、拼接或写入文件。",
    boost: 70,
    apply: "str()",
  },
  {
    label: "bool",
    detail: "转布尔值",
    type: "function",
    info: "按真值规则转为 True/False，空对象一般为 False，常用于条件判断。",
    boost: 68,
    apply: "bool()",
  },
  {
    label: "def",
    detail: "定义函数",
    type: "keyword",
    info: "定义函数，可写位置参数、关键字参数和默认值，是封装和复用代码的基础。",
    boost: 52,
  },
  {
    label: "class",
    detail: "定义类",
    type: "keyword",
    info: "定义类，支持继承和魔术方法，用来创建自定义数据类型。",
    boost: 50,
  },
  {
    label: "with",
    detail: "上下文管理",
    type: "keyword",
    info: "进入上下文管理器，自动处理进入与退出，常用于文件、锁等需要收尾的资源。",
    boost: 48,
  },
  {
    label: "try",
    detail: "异常捕获",
    type: "keyword",
    info: "开始异常处理代码块，后面接 except/finally/else，防止程序因错误直接退出。",
    boost: 46,
  },
  {
    label: "except",
    detail: "处理异常",
    type: "keyword",
    info: "捕获并处理指定异常，与 try 连用，让程序能优雅处理输入或运行时错误。",
    boost: 44,
  },
  {
    label: "finally",
    detail: "收尾",
    type: "keyword",
    info: "无论是否出现异常都会执行的收尾代码块，常用于关闭文件或释放资源。",
    boost: 42,
  },
  {
    label: "import",
    detail: "导入模块",
    type: "keyword",
    info: "导入模块或包中的名称，可用 as 取别名，便于使用标准库或第三方库。",
    boost: 40,
  },
  {
    label: "from",
    detail: "按需导入",
    type: "keyword",
    info: "从模块中按名称导入对象，可与 import/as 组合，减少书写模块前缀。",
    boost: 38,
  },
  {
    label: "return",
    detail: "返回值",
    type: "keyword",
    info: "结束函数并返回一个值，不写时默认返回 None。",
    boost: 36,
  },
  {
    label: "for",
    detail: "for 循环",
    type: "keyword",
    info: "逐项遍历，可以配合 range 使用。",
    boost: 45,
  },
  {
    label: "while",
    detail: "while 循环",
    type: "keyword",
    info: "条件循环，条件为真时执行，支持 break/continue 和 else 分支。",
    boost: 43,
  },
  {
    label: "if",
    detail: "条件分支",
    type: "keyword",
    info: "if 判断，条件成立执行对应语句，可与 elif/else 组成多分支。",
    boost: 41,
    apply: "if ",
  },
  {
    label: "elif",
    detail: "多分支判断",
    type: "keyword",
    info: "否则如果，用来依次判断多个条件，让逻辑更清晰。",
    boost: 39,
    apply: "elif ",
  },
  {
    label: "else",
    detail: "否则",
    type: "keyword",
    info: "否则，在前面条件不满足或循环未提前退出时执行。",
    boost: 37,
    apply: "else:",
  },
  {
    label: "break",
    detail: "退出循环",
    type: "keyword",
    info: "立即终止最近的循环（for 或 while），跳出当前循环体。",
    boost: 35,
  },
  {
    label: "continue",
    detail: "跳过本次",
    type: "keyword",
    info: "结束本轮循环迭代，直接开始下一轮条件判断。",
    boost: 33,
  },
  {
    label: "pass",
    detail: "空操作占位",
    type: "keyword",
    info: "占位语句，不执行任何操作，常用于占位或编写空的函数/类体。",
    boost: 31,
  },
  {
    label: "lambda",
    detail: "匿名函数",
    type: "keyword",
    info: "定义轻量级匿名函数，语法 lambda 参数: 表达式，返回表达式结果，适合简短逻辑。",
    boost: 29,
  },
  {
    label: "yield",
    detail: "生成器产出",
    type: "keyword",
    info: "在函数中产出一个值并暂停状态，把函数变成生成器，可配合 yield from 继续产出。",
    boost: 27,
  },
  {
    label: "global",
    detail: "声明全局变量",
    type: "keyword",
    info: "在函数内部声明写入模块级变量的权限，用于修改外层的全局变量。",
    boost: 25,
  },
  {
    label: "nonlocal",
    detail: "声明外层变量",
    type: "keyword",
    info: "在嵌套函数中声明使用最近外层作用域的变量，便于修改闭包变量。",
    boost: 23,
  },
  {
    label: "True",
    detail: "布尔真",
    type: "keyword",
    info: "布尔常量 True，与 False/None 一起常用于条件表达式和逻辑判断。",
    boost: 21,
  },
  {
    label: "False",
    detail: "布尔假",
    type: "keyword",
    info: "布尔常量 False，在逻辑判断中表示假值，常作为条件的否定结果。",
    boost: 19,
  },
  {
    label: "None",
    detail: "空值对象",
    type: "keyword",
    info: "表示空值或缺失值的单例对象，常用于默认参数或占位。",
    boost: 17,
  },
  {
    label: "and",
    detail: "逻辑与",
    type: "keyword",
    info: "逻辑与运算符，短路求值，返回最后被求值的操作数，常用于多条件同时成立。",
    boost: 15,
  },
  {
    label: "or",
    detail: "逻辑或",
    type: "keyword",
    info: "逻辑或运算符，短路求值，返回第一个真值或最后一个操作数，常用于设默认值。",
    boost: 14,
  },
  {
    label: "not",
    detail: "逻辑非",
    type: "keyword",
    info: "逻辑非运算符，返回布尔取反结果，把真变假、假变真。",
    boost: 13,
  },
  {
    label: "in",
    detail: "成员测试",
    type: "keyword",
    info: "判断元素是否在序列、集合或字典中，返回布尔结果，常用于查找。",
    boost: 12,
  },
  {
    label: "is",
    detail: "身份比较",
    type: "keyword",
    info: "比较两个对象是否是同一个对象，常用于和 None 比较以避免误判。",
    boost: 11,
  },
  {
    label: "append",
    detail: "列表追加",
    type: "method",
    info: "在列表尾部添加一个新元素，等价于 list.append(value)。",
    boost: 48,
    apply: "append()",
  },
  {
    label: "insert",
    detail: "列表插入",
    type: "method",
    info: "在指定位置插入元素，语法 list.insert(index, value)。",
    boost: 46,
    apply: "insert()",
  },
  {
    label: "remove",
    detail: "删除匹配值",
    type: "method",
    info: "删除列表中第一次出现的指定值，不存在会抛出异常 ValueError。",
    boost: 44,
    apply: "remove()",
  },
  {
    label: "pop",
    detail: "弹出元素",
    type: "method",
    info: "移除并返回列表指定位置（默认尾部）的元素，用于栈或队列操作。",
    boost: 42,
    apply: "pop()",
  },
  {
    label: "count",
    detail: "统计次数",
    type: "method",
    info: "返回某个对象在列表中出现的次数，常用于频次统计。",
    boost: 40,
    apply: "count()",
  },
  {
    label: "reverse",
    detail: "反转列表",
    type: "method",
    info: "原地反转列表中元素的顺序，常与切片 [::-1] 效果类似。",
    boost: 38,
    apply: "reverse()",
  },
  {
    label: "sort",
    detail: "列表排序",
    type: "method",
    info: "对列表进行原地排序，可指定 key 排序函数和 reverse 是否倒序。",
    boost: 36,
    apply: "sort()",
  },
  {
    label: "add",
    detail: "集合添加",
    type: "method",
    info: "向集合添加单个元素，若元素已存在则忽略，保持集合去重特性。",
    boost: 50,
    apply: "add()",
  },
  {
    label: "clear",
    detail: "清空集合",
    type: "method",
    info: "移除集合中所有元素，变成一个空集合。",
    boost: 48,
    apply: "clear()",
  },
  {
    label: "keys",
    detail: "字典键",
    type: "method",
    info: "返回字典键的可迭代视图，用于遍历所有键。",
    boost: 42,
    apply: "keys()",
  },
  {
    label: "values",
    detail: "字典值",
    type: "method",
    info: "返回字典值的可迭代视图，用于遍历所有值。",
    boost: 40,
    apply: "values()",
  },
  {
    label: "split",
    detail: "字符串切分",
    type: "method",
    info: "按分隔符切分字符串，返回列表，默认按空白字符分割。",
    boost: 52,
    apply: "split()",
  },
  {
    label: "replace",
    detail: "字符串替换",
    type: "method",
    info: "把字符串中的子串替换为新内容，可限制替换次数。",
    boost: 50,
    apply: "replace()",
  },
  {
    label: "format",
    detail: "格式化字符串",
    type: "method",
    info: "使用占位符或命名参数进行字符串格式化，便于拼接变量输出。",
    boost: 48,
    apply: "format()",
  },
  {
    label: "strip",
    detail: "去首尾字符",
    type: "method",
    info: "移除字符串首尾指定字符，默认移除空白符，常用于清理输入。",
    boost: 46,
    apply: "strip()",
  },
  {
    label: "lower",
    detail: "转小写",
    type: "method",
    info: "把字符串中的字母转换为小写形式，常用于不区分大小写比较。",
    boost: 44,
    apply: "lower()",
  },
  {
    label: "upper",
    detail: "转大写",
    type: "method",
    info: "把字符串中的字母转换为大写形式。",
    boost: 42,
    apply: "upper()",
  },
  {
    label: "swapcase",
    detail: "大小写互换",
    type: "method",
    info: "把字符串中的大小写字母互换，便于切换展示风格。",
    boost: 40,
    apply: "swapcase()",
  },
  {
    label: "find",
    detail: "查找子串位置",
    type: "method",
    info: "返回子串首次出现的索引，未找到返回 -1，适合安全查找。",
    boost: 38,
    apply: "find()",
  },
  {
    label: "index",
    detail: "查找子串索引",
    type: "method",
    info: "返回子串首次出现的索引，未找到会抛出异常 ValueError。",
    boost: 36,
    apply: "index()",
  },
  {
    label: "startswith",
    detail: "前缀判断",
    type: "method",
    info: "判断字符串是否以指定前缀开头，可指定检查的范围切片。",
    boost: 34,
    apply: "startswith()",
  },
  {
    label: "endswith",
    detail: "后缀判断",
    type: "method",
    info: "判断字符串是否以指定后缀结尾，可指定范围，常用于文件名处理。",
    boost: 32,
    apply: "endswith()",
  },
  {
    label: "isalnum",
    detail: "是否字母数字",
    type: "method",
    info: "检测字符串是否只由字母和数字组成，常用于基础输入校验。",
    boost: 30,
    apply: "isalnum()",
  },
  {
    label: "isalpha",
    detail: "是否字母",
    type: "method",
    info: "检测字符串是否只由字母组成，用来判断名字等只含字母的场景。",
    boost: 28,
    apply: "isalpha()",
  },
  {
    label: "isdigit",
    detail: "是否数字",
    type: "method",
    info: "检测字符串是否只由数字组成，用来判断输入是否为纯数字。",
    boost: 26,
    apply: "isdigit()",
  },
  {
    label: "islower",
    detail: "是否全小写",
    type: "method",
    info: "检测字符串是否全部由小写字母组成且至少有一个字母。",
    boost: 24,
    apply: "islower()",
  },
  {
    label: "isupper",
    detail: "是否全大写",
    type: "method",
    info: "检测字符串中所有字母是否都是大写且至少有一个字母。",
    boost: 22,
    apply: "isupper()",
  },
]
