/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module "vue" {
  export interface GlobalComponents {
    NAlert: (typeof import("naive-ui"))["NAlert"]
    NAvatar: (typeof import("naive-ui"))["NAvatar"]
    NButton: (typeof import("naive-ui"))["NButton"]
    NCard: (typeof import("naive-ui"))["NCard"]
    NCheckbox: (typeof import("naive-ui"))["NCheckbox"]
    NCheckboxGroup: (typeof import("naive-ui"))["NCheckboxGroup"]
    NCode: (typeof import("naive-ui"))["NCode"]
    NCollapseTransition: (typeof import("naive-ui"))["NCollapseTransition"]
    NConfigProvider: (typeof import("naive-ui"))["NConfigProvider"]
    NDataTable: (typeof import("naive-ui"))["NDataTable"]
    NDatePicker: (typeof import("naive-ui"))["NDatePicker"]
    NDescriptions: (typeof import("naive-ui"))["NDescriptions"]
    NDescriptionsItem: (typeof import("naive-ui"))["NDescriptionsItem"]
    NDropdown: (typeof import("naive-ui"))["NDropdown"]
    NDynamicTags: (typeof import("naive-ui"))["NDynamicTags"]
    NEmpty: (typeof import("naive-ui"))["NEmpty"]
    NForm: (typeof import("naive-ui"))["NForm"]
    NFormItem: (typeof import("naive-ui"))["NFormItem"]
    NFormItemGi: (typeof import("naive-ui"))["NFormItemGi"]
    NGi: (typeof import("naive-ui"))["NGi"]
    NGradientText: (typeof import("naive-ui"))["NGradientText"]
    NGrid: (typeof import("naive-ui"))["NGrid"]
    NIcon: (typeof import("naive-ui"))["NIcon"]
    NInput: (typeof import("naive-ui"))["NInput"]
    NLayout: (typeof import("naive-ui"))["NLayout"]
    NLayoutContent: (typeof import("naive-ui"))["NLayoutContent"]
    NLayoutHeader: (typeof import("naive-ui"))["NLayoutHeader"]
    NLayoutSider: (typeof import("naive-ui"))["NLayoutSider"]
    NMenu: (typeof import("naive-ui"))["NMenu"]
    NMessageProvider: (typeof import("naive-ui"))["NMessageProvider"]
    NModal: (typeof import("naive-ui"))["NModal"]
    NPagination: (typeof import("naive-ui"))["NPagination"]
    NPopconfirm: (typeof import("naive-ui"))["NPopconfirm"]
    NPopover: (typeof import("naive-ui"))["NPopover"]
    NScrollbar: (typeof import("naive-ui"))["NScrollbar"]
    NSelect: (typeof import("naive-ui"))["NSelect"]
    NSpace: (typeof import("naive-ui"))["NSpace"]
    NSwitch: (typeof import("naive-ui"))["NSwitch"]
    NTabPane: (typeof import("naive-ui"))["NTabPane"]
    NTabs: (typeof import("naive-ui"))["NTabs"]
    NTag: (typeof import("naive-ui"))["NTag"]
    NTooltip: (typeof import("naive-ui"))["NTooltip"]
    NUpload: (typeof import("naive-ui"))["NUpload"]
    RouterLink: (typeof import("vue-router"))["RouterLink"]
    RouterView: (typeof import("vue-router"))["RouterView"]
  }
}
